version: '3'

services:

  jenkins_compose:
    image: jenkins/jenkins
    container_name: jenkinscompose
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes:
      - ../volumes/jenkins:/var/jenkins_home
    networks:
      - docker_network
  
  ubuntu_compose:
    build: ../dockerfiles/slave/.
    container_name: ubuntucompose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins_compose
    networks:
      - docker_network
    command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/New%5Fnode/jenkins-agent.jnlp -secret 8626e7118b4c245c1faee729d1970d6059893b1ae3132ec82d6abcbb24244073 -workDir "/home/"

  selenium_compose:
    image: selenium/hub
    container_name: selenium-hubcompose
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - docker_network
  
  selenium_node_compose:
    image: selenium/node-firefox
    container_name: firefoxcompose
    depends_on:
      - selenium_compose
    environment:
      - SE_EVENT_BUS_HOST=firefoxcompose
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_PUBLISH_PORT=4443
  
  artifactory_compose:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactorycompose
    volumes:
      - ../volumes/artifactory:/var/opt/jfrog/artifactory
    ports:
      - 8081:8081
      - 8082:8082
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge